#!/usr/bin/env bash

usage(){
cat<<'A'
contributter - Contributter(https://contributter.potato4d.me) on Tarminal

Usage: contributter <GH-USERNAME> <DAY-BEFORE>
Args:
- GH-USERNAME GitHub's Username
- DAY-BEFORE  n days ago (default: 1)
A
}

contributter(){
  { (($#<1)) || (($#>2));} && usage && return 1

  local user target_date
  user="$1" day_before="${2-1}"
  target_date="$(date +%Y-%m-%d -d "${day_before} day ago")"
  echo "${user} さんの ${target_date//-//} の contribution 数: $(
    curl -s "https://github.com/users/${user}/contributions" \
      | sed -nE "/data-date=\"${target_date}\"/s/^.*data-count=\"([0-9]+)\".*$/\1/p"
  )"
  echo "#contributter_report"
}

contributter "$@"
exit $?
